[package]
name = "rustlake-api"
version.workspace = true
edition.workspace = true

[[bin]]
name = "rustlake-api"
path = "src/main.rs"

[[bin]]
name = "rustlake"
path = "src/main.rs"

[features]
default = ["duckdb", "postgres", "mysql", "sqlite", "polars"]
# kafka = ["rustlake-stream/kafka"]  # temporarily disabled
duckdb = ["rustlake-engine/duckdb", "dep:duckdb"]
polars = ["rustlake-engine/polars"]
postgres = ["datafusion-table-providers/postgres-federation"]
mysql = ["datafusion-table-providers/mysql-federation", "dep:mysql_async"]
sqlite = ["datafusion-table-providers/sqlite-federation", "datafusion-table-providers/sqlite-bundled", "dep:rusqlite"]
clickhouse = ["datafusion-table-providers/clickhouse-federation"]
odbc = ["datafusion-table-providers/odbc-federation"]
flight-sql-client = ["datafusion-table-providers/flight"]

[dependencies]
rustlake-core = { workspace = true }
rustlake-engine = { workspace = true }
rustlake-router = { workspace = true }
rustlake-stream = { workspace = true }
rustlake-vector = { workspace = true }
rustlake-transform = { workspace = true }
rustlake-flight = { workspace = true }
rand = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
arrow = { workspace = true }
arrow-json = { workspace = true }
arrow-cast = { workspace = true }
arrow-schema = { workspace = true }
parquet = { workspace = true }
datafusion = { workspace = true }
datafusion-table-providers = { workspace = true, optional = true }
datafusion-federation = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tokio-postgres = { workspace = true }
mysql_async = { workspace = true, optional = true }
rusqlite = { workspace = true, optional = true }
mongodb = { workspace = true }
reqwest = { workspace = true }
duckdb = { workspace = true, optional = true }
object_store = { workspace = true }
url = "2"
futures = { workspace = true }
async-trait = { workspace = true }
async-stream = { workspace = true }
regex = "1"
aes-gcm = { workspace = true }
sha2 = { workspace = true }
hostname = { workspace = true }
iceberg = { version = "0.8.0", features = ["storage-s3"] }
