[package]
name = "rustlake-scheduler"
version.workspace = true
edition.workspace = true

[dependencies]
rustlake-core = { workspace = true }
petgraph = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
